# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sqlsaga < Formula
  desc "An interactive terminal game that teaches SQL through a narrative mystery story"
  homepage "https://github.com/bogusdeck/sqlsaga"
  version "0.1.13"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bogusdeck/sqlsaga/releases/download/v0.1.13/sqlsaga_0.1.13_darwin_amd64.tar.gz"
      sha256 "77859855fffdc57d20a3a48ebf7846e027d2fe46df7014a8e5c126874c7a48bc"

      define_method(:install) do
        bin.install "sqlsaga"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bogusdeck/sqlsaga/releases/download/v0.1.13/sqlsaga_0.1.13_darwin_arm64.tar.gz"
      sha256 "f8a687de0f882e72f320d7a36dc2b23ad97c9a5529a9baaa972f5db3c8a72994"

      define_method(:install) do
        bin.install "sqlsaga"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bogusdeck/sqlsaga/releases/download/v0.1.13/sqlsaga_0.1.13_linux_amd64.tar.gz"
      sha256 "c94f3a7487b11ae78b0768a1cab0f1b4332bfee3c4fb28a895e644b6701fad92"
      define_method(:install) do
        bin.install "sqlsaga"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bogusdeck/sqlsaga/releases/download/v0.1.13/sqlsaga_0.1.13_linux_arm64.tar.gz"
      sha256 "0b9836a3ab61fff648f6b00707237069483eb7ae3a824bd3dbe9127c0eeecbb4"
      define_method(:install) do
        bin.install "sqlsaga"
      end
    end
  end

  test do
    system "#{bin}/sqlsaga --version"
  end
end
