# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sqlsaga < Formula
  desc "An interactive terminal game that teaches SQL through a narrative mystery story"
  homepage "https://github.com/bogusdeck/sqlsaga"
  version "0.1.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bogusdeck/sqlsaga/releases/download/v0.1.9/sqlsaga_0.1.9_darwin_amd64.tar.gz"
      sha256 "1f6881a54583ba6a0c1a5b8a9462c3cdb11a369e14254fe8a89f6bf7b3f001bb"

      define_method(:install) do
        bin.install "sqlsaga"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bogusdeck/sqlsaga/releases/download/v0.1.9/sqlsaga_0.1.9_darwin_arm64.tar.gz"
      sha256 "ad6a8efe783172882d5796b05b75924bc80a149ce89712942c7373b5733b6de7"

      define_method(:install) do
        bin.install "sqlsaga"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bogusdeck/sqlsaga/releases/download/v0.1.9/sqlsaga_0.1.9_linux_amd64.tar.gz"
      sha256 "f9fc9f5cc4d9b5676fd19083b27257ca1b85b60114be57061e16345633d060f7"
      define_method(:install) do
        bin.install "sqlsaga"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bogusdeck/sqlsaga/releases/download/v0.1.9/sqlsaga_0.1.9_linux_arm64.tar.gz"
      sha256 "1d113379c250217d67d458e2f1139fae3ac511224dfae7174dcad1738aa978ba"
      define_method(:install) do
        bin.install "sqlsaga"
      end
    end
  end

  test do
    system "#{bin}/sqlsaga --version"
  end
end
