# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sqlsaga < Formula
  desc "An interactive terminal game that teaches SQL through a narrative mystery story"
  homepage "https://github.com/bogusdeck/sqlsaga"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bogusdeck/sqlsaga/releases/download/v0.1.8/sqlsaga_0.1.8_darwin_amd64.tar.gz"
      sha256 "05c6e97ce11c3e263dd4aa785f0070e6c7312297e0baddcc32ab950a385f0ead"

      define_method(:install) do
        bin.install "sqlsaga"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bogusdeck/sqlsaga/releases/download/v0.1.8/sqlsaga_0.1.8_darwin_arm64.tar.gz"
      sha256 "9944e0a83e4b1ac7d8c07b8184c492ff426496488234e054b958395e5ca48ffb"

      define_method(:install) do
        bin.install "sqlsaga"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bogusdeck/sqlsaga/releases/download/v0.1.8/sqlsaga_0.1.8_linux_amd64.tar.gz"
      sha256 "5301adf9816fbe6b6d0399eae0365bd4f52d14865cbb0b80686174dfd627cc33"
      define_method(:install) do
        bin.install "sqlsaga"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bogusdeck/sqlsaga/releases/download/v0.1.8/sqlsaga_0.1.8_linux_arm64.tar.gz"
      sha256 "e31a5259163ea02efcaf61eba3c36f96952dccf5df85e413076bbcd241974d1c"
      define_method(:install) do
        bin.install "sqlsaga"
      end
    end
  end

  test do
    system "#{bin}/sqlsaga --version"
  end
end